### PR TITLE
ProgPoW 0.9.3

### PR DESCRIPTION
**Pull request by ethcoreorg**
Use ProgPoW 0.9.3 version as suggested on Specification https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1057.md#specification - 0.9.2 version is considered as deprecated since it wouldn't benefit mining with AMD card

### CODE REVIEW

**Comment by chfast** [comment]
Why are there test failures?

**Comment by ethcoreorg** [comment]
I have no idea but the test mix hash was generated by multiple clients ( including parity-ethereum https://github.com/paritytech/parity-ethereum/blob/master/ethash/src/progpow.rs#L552 and go-ethereum https://github.com/holiman/go-ethereum/pull/4/files#diff-c1c4f865181db9477a41201783f4bf06L96 )

**Comment by ethcoreorg** [comment]
This seems strange

```
/home/builder/project/test/unittests/test_progpow.cpp:113: Failure
Expected equality of these values:
  sr.mix_hash
    Which is: 32-byte object <F1-37 D1-CC F4-DD 7A-44 7B-14 5C-F9 DD-33 23-01 2F-6F D1-7A F9-43 BC-6C 6D-72 2E-55 73-70 20-22>
  ethash::hash256{}
    Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
/home/builder/project/test/unittests/test_progpow.cpp:114: Failure
Expected equality of these values:
  sr.final_hash
    Which is: 32-byte object <00-C3 FF-9B BC-03 9B-D7 0B-2C 91-C9 58-9C 89-51 C9-E6 8D-43 26-6F C5-0B 5E-B1 51-91 06-5D EC-F0>
  ethash::hash256{}
    Which is: 32-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
/home/builder/project/test/unittests/test_progpow.cpp:115: Failure
Expected equality of these values:
  sr.nonce
    Which is: 11
  0x0
    Which is: 0
/home/builder/project/test/unittests/test_progpow.cpp:125: Failure
Expected equality of these values:
  sr.nonce
    Which is: 157
  185
/home/builder/project/test/unittests/test_progpow.cpp:131: Failure
Expected equality of these values:
  sr.final_hash
    Which is: 32-byte object <00-7A 8F-52 7C-5E 48-69 DE-3C C6-E1 DC-D1 91-AC FA-0A D8-74 24-B7 05-6C 23-FA 7B-4E 62-0A EE-45>
  r.final_hash
    Which is: 32-byte object <DA-13 BC-79 AB-59 9A-94 EF-9D CD-F8 B3-6A DA-15 F2-EA E2-08 C4-D1 5B-55 BD-DE 4B-E2 15-97 A3-3F>
/home/builder/project/test/unittests/test_progpow.cpp:132: Failure
Expected equality of these values:
  sr.mix_hash
    Which is: 32-byte object <99-0B B3-70 F6-7B D2-A5 01-CB F5-9E DB-5B 38-B3 78-02 D2-44 67-C6 32-CA FA-18 6D-A6 5C-D1 31-47>
  r.mix_hash
    Which is: 32-byte object <7A-B9 E7-12 48-AC B6-4A 1B-D3 A4-E2 E4-D9 91-9D F5-C5 61-40 61-6F 75-FE 5C-57 0E-C5 16-BE 8A-8B>
[  FAILED  ] progpow.search (4296 ms)
```

**Comment by chfast** [comment]
@ethcoreorg Can you allow me to push to this PR branch?  I have a fix for this.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by ethcoreorg** [comment]
@chfast Since I couldn't find the "allowing changes" button I've invited you for collaborator instead so you could make a fix https://github.com/ethercore/ethash-1/invitations

**Comment by chfast** [comment]
Thanks.

**Pull request merged**
