### PR TITLE
32bit

### PR DESCRIPTION
**Pull request by chfast**
@gumb0, if you still using MSVC, can you test for me this 32-bit build on Windows? It fails with funny SEH exception on AppVeyor.

### CODE REVIEW

**Comment by gumb0** [comment]
I will check

**Comment by gumb0** [comment]
Yes, it happens to me, too.

Running RelWithDebInfo build under debugger crashes with this stack:

```
 	ethash-test.exe!std::_Func_impl<<lambda_2d406b749f8879e6168ffdeac68e40a6>,std::allocator<int>,ethash::hash1024,ethash_epoch_context const &,unsigned int>::_Do_call(const ethash_epoch_context & <_Args_0>, unsigned int && <_Args_1>) Line 212	C++
>	ethash-test.exe!ethash::`anonymous namespace'::hash_kernel(const ethash_epoch_context & context, const ethash::hash256 & header_hash, unsigned __int64 nonce, const std::function<ethash::hash1024 __cdecl(ethash_epoch_context const &,unsigned int)> & lookup) Line 265	C++
 	ethash-test.exe!ethash::hash(const ethash_epoch_context & context, const ethash::hash256 & header_hash, unsigned __int64 nonce) Line 306	C++
 	ethash-test.exe!ethash_verify_hash_Test::TestBody() Line 576	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	

```

**Comment by gumb0** [comment]
Debug fails to build with runtime mismatch errors

```
1>benchmark.lib(benchmark.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in benchmarks.obj
1>benchmark.lib(benchmark.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in benchmarks.obj
1>benchmark.lib(benchmark_register.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in benchmarks.obj
1>benchmark.lib(benchmark_register.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in benchmarks.obj
...
```

**Comment by chfast** [comment]
Thanks a lot.
For Debug build you can delete https://github.com/chfast/ethash/blob/master/CMakeLists.txt#L17 line. Hunter should build also Debug versions of dependencies. But in Debug testing might take too long.

**Comment by chfast** [comment]
@gumb0, Do you also see it as `unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.`?

**Comment by gumb0** [comment]
yes, I see it when run it not in debugger

**Comment by chfast** [comment]
I replaced `std::function`, but it does not change anything. Can you inspect what argument values are in this call?

**Comment by gumb0** [comment]
I still can't build Debug, but now it looks like this `calloc` fails
```
    context.full_dataset = reinterpret_cast<hash1024*>(std::calloc(num_items, sizeof(hash1024)));
```
`context.full_dataset_size` = 1820327552

`context.full_dataset` is `nullptr` when it is accessed later.

**Comment by chfast** [comment]
Ok, thanks. Added checks for it to the test. Weird, it cannot allocate ~ 2GB of memory...

**Comment by chfast** [comment]
Cool. Confirmed. I will be able to workaround it now. Thanks a lot!

**Comment by chfast** [comment]
The final workaround looks like this: https://github.com/chfast/ethash/pull/24/files#diff-93122c8aa24fccb77a3ac9d3f5ba46e9R577.

**Pull request merged**
